<?php

use App\Http\Controllers\Api\V1\AgentRunController;
use App\Http\Controllers\Api\V1\AIConfigurationController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\ScoringRuleController;
use App\Http\Controllers\Api\V1\CompanyController;
use App\Http\Controllers\Api\V1\DiscoveryController;
use App\Http\Controllers\Api\V1\CampaignController;
use App\Http\Controllers\Api\V1\OutreachController;
use App\Http\Controllers\Api\V1\UnsubscribeController;
use App\Http\Controllers\Api\V1\OutboundWebhookController;
use App\Http\Controllers\Api\V1\ConversationController;
use App\Http\Controllers\Api\V1\SchedulingController;
use App\Http\Controllers\Api\V1\ProposalController;
use App\Http\Controllers\Api\V1\OpportunityController;
use App\Http\Controllers\Api\V1\AgentDecisionController;
use App\Http\Controllers\Api\V1\InboundWebhookController;
use App\Http\Controllers\Api\V1\OrchestrationController;
use App\Http\Controllers\Api\V1\MarketingDraftController;
use App\Http\Controllers\Api\V1\FollowUpRecommendationController;
use App\Http\Controllers\Api\V1\MarketingConfigurationController;
use App\Http\Controllers\Api\V1\SalesController;
use App\Http\Controllers\Api\V1\LocalAcceptanceController;
use App\Http\Middleware\ResolveTenant;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function (): void {
    Route::match(['GET', 'POST'], '/unsubscribe/{enrollment}', UnsubscribeController::class)
        ->middleware(['signed', 'throttle:6,1'])->name('outbound.unsubscribe');
    Route::post('/webhooks/outbound/{provider}', OutboundWebhookController::class)->middleware('throttle:60,1');
    Route::post('/webhooks/inbound/{provider}', InboundWebhookController::class)->middleware('throttle:60,1');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::middleware(['auth:sanctum', ResolveTenant::class])->group(function (): void {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/me', fn () => request()->user());
    Route::get('/tenants', [AuthController::class, 'tenants']);
    Route::get('/dashboard/summary', [CompanyController::class, 'dashboard']);
    Route::get('/contacts', [CompanyController::class, 'contacts']);
    Route::get('/lead-scores', [CompanyController::class, 'scores']);
    Route::get('/website-screenshots/{screenshot}/content', [CompanyController::class, 'screenshotContent']);
    Route::apiResource('companies', CompanyController::class)->only(['index', 'store', 'show']);
    Route::get('/companies/{company}/intelligence', [CompanyController::class, 'intelligence']);
    Route::post('/websites/{website}/scan', [CompanyController::class, 'scan']);
    Route::get('/agent-runs', [AgentRunController::class, 'index']);
    Route::get('/agent-runs/{id}', [AgentRunController::class, 'show']);
    Route::get('/automation/summary', [OrchestrationController::class, 'summary']);
    Route::get('/automation/workflows', [OrchestrationController::class, 'index']);
    Route::post('/automation/workflows', [OrchestrationController::class, 'store']);
    Route::get('/automation/workflows/{id}', [OrchestrationController::class, 'show']);
    Route::post('/automation/workflows/{id}/approvals', [OrchestrationController::class, 'requestApproval']);
    Route::post('/automation/workflows/{id}/{operation}', [OrchestrationController::class, 'control'])->whereIn('operation', ['pause','resume','cancel','retry']);
    Route::get('/automation/approvals', [OrchestrationController::class, 'approvals']);
    Route::post('/automation/approvals/{id}/{decision}', [OrchestrationController::class, 'approve'])->whereIn('decision', ['approve','reject']);
    Route::get('/automation/policies', [OrchestrationController::class, 'policies']);
    Route::put('/automation/policies', [OrchestrationController::class, 'updatePolicies']);
    Route::get('/marketing-drafts', [MarketingDraftController::class, 'index']);
    Route::post('/marketing-drafts', [MarketingDraftController::class, 'generate']);
    Route::post('/marketing-drafts/{id}/regenerate', [MarketingDraftController::class, 'regenerate']);
    Route::patch('/marketing-drafts/{id}', [MarketingDraftController::class, 'update']);
    Route::post('/marketing-drafts/{id}/approve', [MarketingDraftController::class, 'approve']);
    Route::post('/marketing-drafts/{id}/reject', [MarketingDraftController::class, 'reject']);
    Route::get('/follow-up-recommendations', [FollowUpRecommendationController::class, 'index']);
    Route::post('/conversations/{conversation}/follow-up-analysis', [FollowUpRecommendationController::class, 'analyze']);
    Route::post('/follow-up-recommendations/{id}/approve', [FollowUpRecommendationController::class, 'approve']);
    Route::post('/follow-up-recommendations/{id}/reject', [FollowUpRecommendationController::class, 'reject']);
    Route::post('/follow-up-recommendations/{id}/takeover', [FollowUpRecommendationController::class, 'takeover']);
    Route::get('/marketing-configuration/prompts', [MarketingConfigurationController::class, 'prompts']);
    Route::post('/marketing-configuration/prompts', [MarketingConfigurationController::class, 'createPrompt']);
    Route::post('/marketing-configuration/prompts/{id}/approve', [MarketingConfigurationController::class, 'approvePrompt']);
    Route::get('/marketing-configuration/knowledge', [MarketingConfigurationController::class, 'knowledge']);
    Route::post('/marketing-configuration/knowledge', [MarketingConfigurationController::class, 'createKnowledge']);
    Route::post('/marketing-configuration/knowledge/{id}/approve', [MarketingConfigurationController::class, 'approveKnowledge']);
    Route::post('/discovery-runs', [AgentRunController::class, 'discovery']);
    Route::get('/discovery/searches', [DiscoveryController::class, 'searches']);
    Route::get('/discovery/source-health', [DiscoveryController::class, 'sourceHealth']);
    Route::post('/discovery/searches', [DiscoveryController::class, 'createSearch']);
    Route::post('/discovery/searches/{search}/runs', [DiscoveryController::class, 'startRun']);
    Route::get('/discovery/runs', [DiscoveryController::class, 'runs']);
    Route::get('/discovery/runs/{run}', [DiscoveryController::class, 'showRun']);
    Route::get('/discovery/candidates', [DiscoveryController::class, 'candidates']);
    Route::get('/discovery/candidates/{candidate}', [DiscoveryController::class, 'candidate']);
    Route::post('/discovery/candidates/bulk-review', [DiscoveryController::class, 'bulkReview']);
    Route::post('/discovery/candidates/{candidate}/review', [DiscoveryController::class, 'review']);
    Route::post('/discovery/import/preview', [DiscoveryController::class, 'previewImport']);
    Route::post('/discovery/import', [DiscoveryController::class, 'import']);
    Route::post('/companies/{company}/score', [AgentRunController::class, 'scoreCompany']);
    Route::get('/ai-configurations', [AIConfigurationController::class, 'index']);
    Route::post('/ai-configurations', [AIConfigurationController::class, 'store']);
    Route::put('/ai-configurations/{id}', [AIConfigurationController::class, 'update']);
    Route::get('/scoring-rules', [ScoringRuleController::class, 'show']);
    Route::put('/scoring-rules', [ScoringRuleController::class, 'update']);
    Route::get('/campaigns', [CampaignController::class, 'index']);
    Route::post('/campaigns', [CampaignController::class, 'store']);
    Route::get('/campaigns/{campaign}', [CampaignController::class, 'show']);
    Route::patch('/campaigns/{campaign}', [CampaignController::class, 'update']);
    Route::post('/campaigns/{campaign}/templates', [CampaignController::class, 'storeTemplate']);
    Route::post('/campaigns/{campaign}/templates/{template}/approve', [CampaignController::class, 'approveTemplate']);
    Route::post('/campaigns/{campaign}/steps', [CampaignController::class, 'storeStep']);
    Route::patch('/campaigns/{campaign}/steps/{step}', [CampaignController::class, 'updateStep']);
    Route::delete('/campaigns/{campaign}/steps/{step}', [CampaignController::class, 'deleteStep']);
    Route::get('/campaigns/{campaign}/steps', [CampaignController::class, 'steps']);
    Route::put('/campaigns/{campaign}/steps/reorder', [CampaignController::class, 'reorderSteps']);
    Route::get('/campaigns/{campaign}/enrollments', [CampaignController::class, 'enrollments']);
    Route::post('/campaigns/{campaign}/enrollments', [CampaignController::class, 'enroll']);
    Route::post('/campaigns/{campaign}/enrollments/{enrollment}/stop', [CampaignController::class, 'stopEnrollment']);
    Route::post('/campaigns/{campaign}/activate', [CampaignController::class, 'activate']);
    Route::post('/campaigns/{campaign}/start', [CampaignController::class, 'activate']);
    Route::post('/campaigns/{campaign}/pause', [CampaignController::class, 'pause']);
    Route::post('/campaigns/{campaign}/resume', [CampaignController::class, 'resume']);
    Route::post('/campaigns/{campaign}/complete', [CampaignController::class, 'complete']);
    Route::post('/campaigns/{campaign}/cancel', [CampaignController::class, 'cancel']);
    Route::get('/outbound-messages', [OutreachController::class, 'messages']);
    Route::get('/outbound-messages/{message}', [OutreachController::class, 'showMessage']);
    Route::get('/suppressions', [OutreachController::class, 'suppressions']);
    Route::post('/suppressions', [OutreachController::class, 'createSuppression']);
    Route::get('/messaging-configuration', [CampaignController::class, 'messagingConfiguration']);
    Route::put('/messaging-configuration', [CampaignController::class, 'updateMessagingConfiguration']);
    Route::get('/conversations', [ConversationController::class, 'index']);
    Route::get('/conversations/{id}', [ConversationController::class, 'show']);
    Route::post('/conversations/{id}/classify', [ConversationController::class, 'classify']);
    Route::post('/conversations/{id}/reply-drafts', [ConversationController::class, 'draftReply']);
    Route::put('/conversations/{id}/reply-drafts/{draftId}', [ConversationController::class, 'updateReplyDraft']);
    Route::post('/conversations/{id}/reply-drafts/{draftId}/approve', [ConversationController::class, 'approveReply']);
    Route::post('/conversations/{id}/takeover', [ConversationController::class, 'takeover']);
    Route::post('/conversations/{id}/resolve', [ConversationController::class, 'resolve']);
    Route::post('/conversations/{conversation}/sales-analysis', [SalesController::class, 'analyze']);
    Route::post('/conversations/{id}/return-to-ai', [SalesController::class, 'returnToAi']);
    Route::put('/conversations/{id}/qualification', [SalesController::class, 'qualification']);
    Route::get('/sales-drafts', [SalesController::class, 'drafts']);
    Route::post('/sales-drafts/{id}/regenerate', [SalesController::class, 'regenerate']);
    Route::post('/sales-drafts/{id}/{decision}', [SalesController::class, 'reviewDraft'])->whereIn('decision', ['approve','reject']);
    Route::get('/handoff-queue', [SalesController::class, 'handoffQueue']);
    Route::get('/sales-pipeline', [SalesController::class, 'pipeline']);
    Route::get('/sales-policy', [SalesController::class, 'policy']);
    Route::put('/sales-policy', [SalesController::class, 'updatePolicy']);
    Route::get('/scheduling-configuration', [SchedulingController::class, 'configuration']);
    Route::put('/scheduling-configuration', [SchedulingController::class, 'updateConfiguration']);
    Route::post('/conversations/{conversation}/scheduling-requests', [SchedulingController::class, 'createRequest']);
    Route::get('/scheduling-requests/{schedulingRequest}', [SchedulingController::class, 'showRequest']);
    Route::post('/scheduling-requests/{schedulingRequest}/availability', [SchedulingController::class, 'requestAvailability']);
    Route::post('/scheduling-requests/{schedulingRequest}/select-slot', [SchedulingController::class, 'selectSlot']);
    Route::post('/scheduling-requests/{schedulingRequest}/book', [SchedulingController::class, 'bookSelected']);
    Route::post('/scheduling-requests/{schedulingRequest}/cancel', [SchedulingController::class, 'cancelRequest']);
    Route::get('/meetings', [SchedulingController::class, 'meetings']);
    Route::get('/meetings/{booking}', [SchedulingController::class, 'meeting']);
    Route::post('/meetings/{booking}/cancel', [SchedulingController::class, 'cancelMeeting']);
    Route::patch('/meetings/{booking}/status', [SchedulingController::class, 'updateMeetingStatus']);
    Route::get('/opportunities', [OpportunityController::class, 'index']);
    Route::post('/opportunities', [OpportunityController::class, 'store']);
    Route::get('/opportunities/{id}', [SalesController::class, 'opportunity']);
    Route::put('/opportunities/{id}/stage', [SalesController::class, 'updateStage']);
    Route::put('/opportunities/{id}/value', [SalesController::class, 'updateValue']);
    Route::post('/opportunities/{id}/qualified', [SalesController::class, 'markQualified']);
    Route::post('/opportunities/{id}/not-qualified', [SalesController::class, 'markNotQualified']);
    Route::get('/tenant-services', [ProposalController::class, 'services']);
    Route::post('/tenant-services', [ProposalController::class, 'storeService']);
    Route::patch('/tenant-services/{service}', [ProposalController::class, 'updateService']);
    Route::post('/tenant-services/{service}/deactivate', [ProposalController::class, 'deactivateService']);
    Route::get('/pricing-policy', [ProposalController::class, 'pricingPolicy']);
    Route::put('/pricing-policy', [ProposalController::class, 'updatePricingPolicy']);
    Route::get('/proposals', [ProposalController::class, 'index']);
    Route::get('/proposals/{id}', [ProposalController::class, 'show']);
    Route::post('/opportunities/{opportunity}/proposals', [ProposalController::class, 'create']);
    Route::get('/proposals/{id}/versions', [ProposalController::class, 'versions']);
    Route::post('/proposals/{proposal}/internal-notes', [ProposalController::class, 'addInternalNote']);
    Route::patch('/proposals/{proposal}/requirements', [ProposalController::class, 'updateRequirements']);
    Route::post('/proposals/{proposal}/generate', [ProposalController::class, 'generate']);
    Route::post('/proposals/{proposal}/regenerate', [ProposalController::class, 'generate']);
    Route::patch('/proposals/{proposal}/versions/{version}', [ProposalController::class, 'updateDraft']);
    Route::put('/proposals/{proposal}/commercials', [ProposalController::class, 'updateCommercials']);
    Route::post('/proposals/{proposal}/approve', [ProposalController::class, 'approve']);
    Route::post('/proposals/{proposal}/reject', [ProposalController::class, 'reject']);
    Route::post('/proposals/{proposal}/supersede', [ProposalController::class, 'supersede']);
    Route::post('/proposals/{proposal}/document', [ProposalController::class, 'generateDocument']);
    Route::get('/proposals/{proposal}/versions/{version}/document', [ProposalController::class, 'downloadDocument']);
    Route::post('/proposals/{proposal}/ready-to-send', [ProposalController::class, 'readyToSend']);
    Route::get('/agent-decisions', [AgentDecisionController::class, 'index']);
    Route::get('/agent-decisions/{id}', [AgentDecisionController::class, 'show']);
    Route::post('/agent-decisions/{id}/approve', [AgentDecisionController::class, 'approve']);
    Route::post('/agent-decisions/{id}/reject', [AgentDecisionController::class, 'reject']);
    Route::get('/local-acceptance/status', [LocalAcceptanceController::class, 'status']);
    Route::post('/local-acceptance/outbound/{message}/sent', [LocalAcceptanceController::class, 'markSent']);
    Route::post('/local-acceptance/reply', [LocalAcceptanceController::class, 'simulateReply']);
    });
});
