<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('tenants', function (Blueprint $t) { $t->uuid('id')->primary(); $t->string('name'); $t->string('slug')->unique(); $t->string('status')->default('active'); $t->jsonb('settings')->nullable(); $t->timestampsTz(); });
        Schema::create('users', function (Blueprint $t) { $t->id(); $t->string('name'); $t->string('email')->unique(); $t->timestampTz('email_verified_at')->nullable(); $t->string('password'); $t->rememberToken(); $t->timestampsTz(); });
        Schema::create('tenant_user', function (Blueprint $t) { $t->uuid('tenant_id'); $t->foreign('tenant_id')->references('id')->on('tenants')->cascadeOnDelete(); $t->foreignId('user_id')->constrained()->cascadeOnDelete(); $t->string('role')->default('member'); $t->string('status')->default('active'); $t->timestampsTz(); $t->primary(['tenant_id', 'user_id']); });
        Schema::create('personal_access_tokens', function (Blueprint $t) { $t->id(); $t->morphs('tokenable'); $t->string('name'); $t->string('token', 64)->unique(); $t->text('abilities')->nullable(); $t->timestampTz('last_used_at')->nullable(); $t->timestampTz('expires_at')->nullable()->index(); $t->timestamps(); });
        Schema::create('failed_jobs', function (Blueprint $t) { $t->id(); $t->string('uuid')->unique(); $t->text('connection'); $t->text('queue'); $t->longText('payload'); $t->longText('exception'); $t->timestampTz('failed_at')->useCurrent(); });
        Schema::create('job_batches', function (Blueprint $t) { $t->string('id')->primary(); $t->string('name'); $t->integer('total_jobs'); $t->integer('pending_jobs'); $t->integer('failed_jobs'); $t->longText('failed_job_ids'); $t->mediumText('options')->nullable(); $t->integer('cancelled_at')->nullable(); $t->integer('created_at'); $t->integer('finished_at')->nullable(); });
        $tenant = fn (Blueprint $t) => $t->foreignUuid('tenant_id')->constrained('tenants')->cascadeOnDelete();
        Schema::create('companies', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('name'); $t->string('normalized_domain')->nullable(); $t->string('industry')->nullable(); $t->string('location')->nullable(); $t->text('description')->nullable(); $t->string('source')->nullable(); $t->string('status')->default('new'); $t->timestampsTz(); $t->index(['tenant_id', 'status']); $t->unique(['tenant_id', 'normalized_domain']); });
        Schema::create('company_websites', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->text('url'); $t->string('host'); $t->text('canonical_url')->nullable(); $t->string('verification_status')->default('unverified'); $t->string('source')->nullable(); $t->timestampsTz(); $t->unique(['tenant_id', 'company_id', 'host']); $t->index(['tenant_id', 'company_id']); });
        Schema::create('contacts', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->string('name')->nullable(); $t->string('title')->nullable(); $t->text('public_profile_url')->nullable(); $t->text('source_url'); $t->timestampTz('observed_at'); $t->string('extraction_method'); $t->decimal('confidence', 5, 4); $t->timestampsTz(); $t->index(['tenant_id', 'company_id']); });
        Schema::create('contact_methods', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('contact_id')->constrained()->cascadeOnDelete(); $t->string('type'); $t->text('value'); $t->text('source_url'); $t->timestampTz('observed_at'); $t->string('extraction_method'); $t->decimal('confidence', 5, 4); $t->string('verification_status')->default('unverified'); $t->timestampsTz(); $t->index(['tenant_id', 'contact_id']); });
        Schema::create('website_scans', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_website_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('queued'); $t->unsignedSmallInteger('max_depth')->default(2); $t->unsignedSmallInteger('max_pages')->default(30); $t->string('crawler_version')->nullable(); $t->jsonb('policy_snapshot')->nullable(); $t->text('error_summary')->nullable(); $t->timestampTz('started_at')->nullable(); $t->timestampTz('finished_at')->nullable(); $t->timestampsTz(); $t->index(['tenant_id', 'status']); });
        Schema::create('website_pages', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('website_scan_id')->constrained()->cascadeOnDelete(); $t->text('requested_url'); $t->text('final_url')->nullable(); $t->text('canonical_url')->nullable(); $t->unsignedSmallInteger('http_status')->nullable(); $t->string('content_type')->nullable(); $t->string('title')->nullable(); $t->timestampTz('fetched_at')->nullable(); $t->string('content_hash', 64)->nullable(); $t->text('object_key')->nullable(); $t->text('extracted_text')->nullable(); $t->unsignedSmallInteger('depth')->default(0); $t->timestampsTz(); $t->index(['tenant_id', 'website_scan_id']); $t->index(['website_scan_id', 'content_hash']); });
        Schema::create('website_screenshots', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('website_scan_id')->constrained()->cascadeOnDelete(); $t->foreignUuid('website_page_id')->nullable()->constrained()->nullOnDelete(); $t->text('object_key'); $t->string('viewport'); $t->string('content_hash', 64)->nullable(); $t->timestampTz('captured_at')->nullable(); $t->string('status')->default('stored'); $t->timestampsTz(); });
        Schema::create('website_technologies', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('website_scan_id')->constrained()->cascadeOnDelete(); $t->string('name'); $t->string('category')->nullable(); $t->string('detection_method'); $t->decimal('confidence', 5, 4); $t->foreignUuid('website_page_id')->nullable()->constrained()->nullOnDelete(); $t->timestampsTz(); });
        Schema::create('website_issues', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('website_scan_id')->constrained()->cascadeOnDelete(); $t->string('type'); $t->string('severity'); $t->text('summary'); $t->foreignUuid('website_page_id')->nullable()->constrained()->nullOnDelete(); $t->jsonb('evidence')->nullable(); $t->decimal('confidence', 5, 4); $t->string('detector_version')->nullable(); $t->timestampsTz(); });
        Schema::create('lead_scores', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->unsignedTinyInteger('score'); $t->jsonb('components'); $t->unsignedInteger('rule_version'); $t->uuid('agent_run_id')->nullable(); $t->timestampTz('scored_at'); $t->timestampsTz(); $t->index(['tenant_id', 'company_id', 'scored_at']); });
        Schema::create('lead_insights', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->string('kind'); $t->text('statement'); $t->decimal('confidence', 5, 4); $t->uuid('agent_run_id')->nullable(); $t->timestampsTz(); });
        Schema::create('lead_evidence', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('lead_insight_id')->constrained()->cascadeOnDelete(); $t->string('evidence_type'); $t->text('source_url')->nullable(); $t->text('excerpt')->nullable(); $t->string('content_hash', 64)->nullable(); $t->timestampTz('observed_at'); $t->decimal('confidence', 5, 4); $t->timestampsTz(); });
        Schema::create('campaigns', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('name'); $t->string('status')->default('draft'); $t->jsonb('configuration')->nullable(); $t->timestampsTz(); });
        Schema::create('campaign_steps', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('campaign_id')->constrained()->cascadeOnDelete(); $t->unsignedSmallInteger('ordinal'); $t->string('step_type'); $t->unsignedInteger('delay_seconds')->default(0); $t->jsonb('configuration')->nullable(); $t->timestampsTz(); $t->unique(['campaign_id', 'ordinal']); });
        Schema::create('campaign_recipients', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('campaign_id')->constrained()->cascadeOnDelete(); $t->foreignUuid('company_id')->nullable()->constrained()->nullOnDelete(); $t->foreignUuid('contact_id')->nullable()->constrained()->nullOnDelete(); $t->string('status')->default('pending'); $t->string('suppression_outcome')->nullable(); $t->timestampsTz(); });
        Schema::create('campaign_events', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('campaign_recipient_id')->constrained()->cascadeOnDelete(); $t->string('event_type'); $t->jsonb('metadata')->nullable(); $t->timestampTz('occurred_at'); $t->timestampsTz(); });
        Schema::create('conversations', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->foreignUuid('contact_id')->nullable()->constrained()->nullOnDelete(); $t->string('channel'); $t->string('status')->default('open'); $t->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $t->timestampsTz(); });
        Schema::create('conversation_messages', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('conversation_id')->constrained()->cascadeOnDelete(); $t->string('direction'); $t->text('body'); $t->string('delivery_status')->nullable(); $t->jsonb('provider_metadata')->nullable(); $t->timestampTz('sent_at')->nullable(); $t->timestampsTz(); });
        Schema::create('sales_opportunities', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('company_id')->constrained()->cascadeOnDelete(); $t->foreignId('owner_user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('stage')->default('new'); $t->decimal('value', 14, 2)->nullable(); $t->char('currency', 3)->nullable(); $t->string('status')->default('open'); $t->jsonb('qualification')->nullable(); $t->timestampsTz(); });
        Schema::create('opportunity_activities', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('sales_opportunity_id')->constrained()->cascadeOnDelete(); $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('activity_type'); $t->jsonb('details')->nullable(); $t->timestampTz('occurred_at'); $t->timestampsTz(); });
        Schema::create('proposals', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('sales_opportunity_id')->constrained()->cascadeOnDelete(); $t->string('status')->default('draft'); $t->unsignedInteger('version')->default(1); $t->text('object_key')->nullable(); $t->decimal('total', 14, 2)->nullable(); $t->char('currency', 3)->nullable(); $t->timestampTz('approved_at')->nullable(); $t->timestampsTz(); });
        Schema::create('agent_runs', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('agent_key'); $t->string('status')->default('queued'); $t->foreignId('requested_by')->nullable()->constrained('users')->nullOnDelete(); $t->string('input_hash', 64)->nullable(); $t->string('output_hash', 64)->nullable(); $t->string('configuration_version')->nullable(); $t->text('summary')->nullable(); $t->text('error_summary')->nullable(); $t->string('idempotency_key')->nullable(); $t->timestampTz('started_at')->nullable(); $t->timestampTz('finished_at')->nullable(); $t->timestampsTz(); $t->index(['tenant_id', 'agent_key', 'status']); $t->unique(['tenant_id', 'idempotency_key']); });
        Schema::create('agent_events', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignUuid('agent_run_id')->constrained()->cascadeOnDelete(); $t->unsignedInteger('sequence'); $t->string('event_key'); $t->jsonb('payload')->nullable(); $t->timestampTz('created_at')->useCurrent(); $t->unique(['agent_run_id', 'sequence']); });
        Schema::table('lead_scores', function (Blueprint $t) { $t->foreign('agent_run_id')->references('id')->on('agent_runs')->nullOnDelete(); });
        Schema::table('lead_insights', function (Blueprint $t) { $t->foreign('agent_run_id')->references('id')->on('agent_runs')->nullOnDelete(); });
        Schema::create('ai_model_configurations', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('task_key'); $t->string('provider'); $t->string('model'); $t->boolean('enabled')->default(true); $t->jsonb('parameters')->nullable(); $t->string('secret_reference')->nullable(); $t->unsignedInteger('version')->default(1); $t->timestampsTz(); $t->unique(['tenant_id', 'task_key']); });
        Schema::create('prompt_templates', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('agent_key'); $t->unsignedInteger('version'); $t->text('template'); $t->string('schema_version'); $t->boolean('active')->default(false); $t->timestampsTz(); $t->unique(['tenant_id', 'agent_key', 'version']); });
        Schema::create('suppression_lists', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->string('identifier_hash', 64); $t->string('reason'); $t->string('source')->nullable(); $t->timestampsTz(); $t->unique(['tenant_id', 'identifier_hash']); });
        Schema::create('audit_logs', function (Blueprint $t) use ($tenant) { $t->uuid('id')->primary(); $tenant($t); $t->foreignId('actor_user_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('action'); $t->string('subject_type')->nullable(); $t->uuid('subject_id')->nullable(); $t->string('request_id')->nullable(); $t->jsonb('metadata')->nullable(); $t->timestampTz('created_at')->useCurrent(); $t->index(['tenant_id', 'created_at']); });
    }

    public function down(): void
    {
        foreach (['audit_logs','suppression_lists','prompt_templates','ai_model_configurations','proposals','opportunity_activities','sales_opportunities','conversation_messages','conversations','campaign_events','campaign_recipients','campaign_steps','campaigns','lead_evidence','lead_insights','lead_scores','website_issues','website_technologies','website_screenshots','website_pages','website_scans','contact_methods','contacts','company_websites','agent_events','agent_runs','companies','job_batches','failed_jobs','personal_access_tokens','tenant_user','users','tenants'] as $table) Schema::dropIfExists($table);
    }
};
