<?php

return [
    'max_candidates_per_run' => (int) env('DISCOVERY_MAX_CANDIDATES_PER_RUN', 100),
    'max_csv_rows' => (int) env('DISCOVERY_MAX_CSV_ROWS', 500),
    'max_websites_verified_per_run' => (int) env('DISCOVERY_MAX_VERIFICATIONS_PER_RUN', 100),
    'max_pages_per_domain' => (int) env('DISCOVERY_MAX_PAGES_PER_DOMAIN', 10),
    'max_browser_renders_per_run' => (int) env('DISCOVERY_MAX_BROWSER_RENDERS_PER_RUN', 0),
    'max_ai_analyses_per_run' => (int) env('DISCOVERY_MAX_AI_ANALYSES_PER_RUN', 25),
    'max_runtime_seconds' => (int) env('DISCOVERY_MAX_RUNTIME_SECONDS', 600),
    'allow_deterministic' => env('DISCOVERY_ALLOW_DETERMINISTIC', false),
    'overpass_endpoint' => env('DISCOVERY_OVERPASS_ENDPOINT', 'https://overpass-api.de/api/interpreter'),
    'overpass_allowed_hosts' => array_filter(array_map('trim', explode(',', env('DISCOVERY_OVERPASS_ALLOWED_HOSTS', 'overpass-api.de')))),
    'osm_user_agent' => env('DISCOVERY_OSM_USER_AGENT', 'YaanduGrowthEngine/1.0 (+https://yaandu.ai)'),
    'osm_enabled' => env('DISCOVERY_OSM_ENABLED', true),
    'osm_timeout_seconds' => (int) env('DISCOVERY_OSM_TIMEOUT_SECONDS', 20),
    'osm_retries' => (int) env('DISCOVERY_OSM_RETRIES', 2),
    'osm_min_delay_ms' => (int) env('DISCOVERY_OSM_MIN_DELAY_MS', 1000),
    'osm_cache_ttl_seconds' => (int) env('DISCOVERY_OSM_CACHE_TTL_SECONDS', 21600),
    'osm_max_queries_per_run' => (int) env('DISCOVERY_OSM_MAX_QUERIES_PER_RUN', 1),
    'osm_max_radius_m' => (int) env('DISCOVERY_OSM_MAX_RADIUS_M', 25000),
    'osm_max_bbox_area_degrees' => (float) env('DISCOVERY_OSM_MAX_BBOX_AREA_DEGREES', 0.5),
    'osm_max_elements' => (int) env('DISCOVERY_OSM_MAX_ELEMENTS', 100),
    'osm_max_response_bytes' => (int) env('DISCOVERY_OSM_MAX_RESPONSE_BYTES', 2000000),
    'osm_categories' => [
        'furniture' => ['shop' => ['furniture']], 'home decor' => ['shop' => ['interior_decoration', 'houseware', 'furniture']],
        'retail' => ['shop' => ['*']], 'office' => ['office' => ['*']],
        'interior design' => ['shop' => ['interior_decoration']],
        'jewellery' => ['shop' => ['jewelry']],
        'electronics' => ['shop' => ['electronics']],
        'fashion' => ['shop' => ['clothes']], 'clothing' => ['shop' => ['clothes']],
        'textile' => ['shop' => ['fabric']],
        'hospitality' => ['amenity' => ['restaurant', 'cafe', 'hotel']],
        'healthcare' => ['healthcare' => ['*'], 'amenity' => ['doctors', 'clinic', 'dentist']],
        'business' => ['shop' => ['*'], 'office' => ['*'], 'craft' => ['*']],
    ],
    'locations' => [
        'Dubai' => ['city' => 'Dubai', 'country' => 'UAE', 'bbox' => [24.75, 54.85, 25.35, 55.60]],
        'Abu Dhabi' => ['city' => 'Abu Dhabi', 'country' => 'UAE', 'bbox' => [24.20, 54.90, 24.65, 55.10]],
        'Sharjah' => ['city' => 'Sharjah', 'country' => 'UAE', 'bbox' => [25.20, 55.30, 25.45, 55.55]],
        'Coimbatore' => ['city' => 'Coimbatore', 'country' => 'India', 'region' => 'Tamil Nadu', 'bbox' => [10.90, 76.85, 11.15, 77.10]],
        'Salem' => ['city' => 'Salem', 'country' => 'India', 'region' => 'Tamil Nadu', 'bbox' => [11.60, 78.05, 11.80, 78.25]],
    ],
    'analysis_min_cheap_score' => (int) env('DISCOVERY_ANALYSIS_MIN_CHEAP_SCORE', 1),
];
