<?php

return [
    'enabled' => (bool) env('WEBSITE_RESOLUTION_ENABLED', true),
    'auto_resolve_high_confidence' => (bool) env('WEBSITE_RESOLUTION_AUTO_RESOLVE_HIGH_CONFIDENCE', false),
    'max_businesses_per_run' => (int) env('WEBSITE_RESOLUTION_MAX_BUSINESSES_PER_RUN', 25),
    'max_businesses_per_request' => (int) env('WEBSITE_RESOLUTION_MAX_BUSINESSES_PER_REQUEST', 10),
    'max_source_lookups_per_business' => (int) env('WEBSITE_RESOLUTION_MAX_SOURCE_LOOKUPS', 4),
    'max_candidate_domains_per_business' => (int) env('WEBSITE_RESOLUTION_MAX_CANDIDATE_DOMAINS', 5),
    'max_candidate_pages_per_domain' => (int) env('WEBSITE_RESOLUTION_MAX_PAGES_PER_DOMAIN', 1),
    'max_duration_seconds' => (int) env('WEBSITE_RESOLUTION_MAX_DURATION_SECONDS', 60),
    'max_concurrent_resolutions' => (int) env('WEBSITE_RESOLUTION_MAX_CONCURRENT', 1),
    'max_candidate_page_bytes' => (int) env('WEBSITE_RESOLUTION_MAX_PAGE_BYTES', 1000000),
    'user_agent' => env('WEBSITE_RESOLUTION_USER_AGENT', 'YaanduWebsiteResolution/1.0 (+https://yaandu.ai)'),
    'wikidata_cache_seconds' => (int) env('WEBSITE_RESOLUTION_WIKIDATA_CACHE_SECONDS', 604800),
    'common_crawl_cache_seconds' => (int) env('WEBSITE_RESOLUTION_COMMON_CRAWL_CACHE_SECONDS', 604800),
    'candidate_page_cache_seconds' => (int) env('WEBSITE_RESOLUTION_CANDIDATE_PAGE_CACHE_SECONDS', 86400),
    'common_crawl_collection' => env('WEBSITE_RESOLUTION_COMMON_CRAWL_COLLECTION'),
    'common_crawl_records_per_domain' => (int) env('WEBSITE_RESOLUTION_COMMON_CRAWL_RECORDS_PER_DOMAIN', 2),
    'common_crawl_min_interval_ms' => (int) env('WEBSITE_RESOLUTION_COMMON_CRAWL_MIN_INTERVAL_MS', 2000),
    'max_common_crawl_lookups' => (int) env('WEBSITE_RESOLUTION_MAX_COMMON_CRAWL_LOOKUPS', 3),
    'local_index_results_per_business' => (int) env('WEBSITE_RESOLUTION_LOCAL_INDEX_RESULTS', 10),
    'osm_index_city' => env('WEBSITE_RESOLUTION_OSM_INDEX_CITY', 'Dubai'),
    'osm_index_country' => env('WEBSITE_RESOLUTION_OSM_INDEX_COUNTRY', 'UAE'),
    'osm_index_queries_per_ingestion' => (int) env('WEBSITE_RESOLUTION_OSM_INDEX_QUERIES', 4),
    'osm_index_max_fetch_attempts' => (int) env('WEBSITE_RESOLUTION_OSM_INDEX_MAX_FETCHES', 100),
    'index_ingestion_max_duration_seconds' => (int) env('WEBSITE_INDEX_INGESTION_MAX_DURATION_SECONDS', 300),
    'high_confidence_threshold' => (int) env('WEBSITE_RESOLUTION_HIGH_THRESHOLD', 85),
    'medium_confidence_threshold' => (int) env('WEBSITE_RESOLUTION_MEDIUM_THRESHOLD', 50),
    'score' => [
        'name_match' => 35, 'phone_match' => 45, 'email_match' => 50,
        'location_match' => 20, 'address_match' => 20, 'country_contradiction' => -35,
        'structured_data_match' => 15, 'social_corroboration' => 8, 'parked_domain' => -80,
        'email_domain_match' => 20, 'wikidata_brand_website' => 30, 'wikidata_operator_website' => 40,
    ],
    'deterministic_fixtures' => [],
];
