<script setup lang="ts">
import { onMounted, ref } from 'vue'
const props = defineProps<{ tenantId: string }>()
const campaigns = ref<any[]>([]); const events = ref<any[]>([]); const selected = ref(''); const error = ref(''); const loading = ref(false)
const labels: Record<string,string> = { campaign_created:'Campaign created',campaign_started:'Campaign started',campaign_paused:'Campaign paused',campaign_resumed:'Campaign resumed',campaign_completed:'Campaign completed',campaign_cancelled:'Campaign cancelled',enrolled:'Prospect enrolled',step_scheduled:'Next step scheduled',message_queued:'Message queued',message_sent:'Message sent',message_accepted:'Message accepted by provider',message_failed:'Message failed',message_suppressed:'Message blocked by suppression rules',contact_replied:'Reply received',contact_unsubscribed:'Prospect unsubscribed',unsubscribed:'Prospect unsubscribed',contact_manually_suppressed:'Address suppressed',enrollment_stopped:'Sequence stopped' }
async function request(path:string){const r=await fetch('/api/v1'+path,{credentials:'include',headers:{Accept:'application/json','X-Tenant-ID':props.tenantId}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Unable to load activity.');return d}
async function load(){loading.value=true;error.value='';try{const result=await request('/campaigns');campaigns.value=result.data??[];if(!selected.value&&campaigns.value.length)selected.value=campaigns.value[0].id;if(selected.value){const campaign=await request('/campaigns/'+encodeURIComponent(selected.value));events.value=campaign.events??[]}}catch(e){error.value=e instanceof Error?e.message:'Unable to load campaign activity.'}finally{loading.value=false}}
onMounted(()=>void load())
</script>
<template><section class="campaign-activity"><div class="test-mode-banner"><b>TEST MODE</b><span>Message activity uses the fake provider and is not external delivery.</span></div><div class="panel activity-panel"><div class="panel-heading"><div><h2>Campaign activity</h2><p>Human-readable events from the campaign and message ledger.</p></div><button class="quiet" @click="load">↻ Refresh</button></div><label>Campaign<select v-model="selected" @change="load"><option v-for="c in campaigns" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><div v-if="error" class="notice">{{ error }}</div><div v-if="loading" class="empty-table">Loading campaign activity…</div><ol v-else-if="events.length" class="activity-timeline"><li v-for="event in events" :key="event.id"><span class="activity-dot"></span><div><b>{{ labels[event.event_type] || 'Campaign updated' }}</b><small>{{ new Date(event.occurred_at).toLocaleString() }}</small></div></li></ol><div v-else class="empty-table">No activity recorded yet. Draft creation and campaign lifecycle events appear here.</div><small class="activity-note">Only supported business events are shown. Technical event payloads are available in Operations.</small></div></section></template>
<style scoped>.campaign-activity{display:grid;gap:14px}.campaign-activity label{display:flex;gap:10px;align-items:center;color:#56647a;font-size:11px}.campaign-activity select{max-width:360px;min-width:180px;padding:8px;border:1px solid #e0e5ec;border-radius:6px;background:#fff}.activity-timeline{list-style:none;margin:0;padding:4px 0 4px 10px;border-left:1px solid #e5e9ef;display:grid;gap:0}.activity-timeline li{position:relative;display:flex;gap:12px;padding:10px 0 10px 12px}.activity-dot{position:absolute;left:-15px;top:15px;width:9px;height:9px;border:2px solid #fff;border-radius:50%;background:#687abc;box-shadow:0 0 0 1px #687abc}.activity-timeline b{display:block;color:#344257;font-size:11px}.activity-timeline small,.activity-note{display:block;margin-top:4px;color:#8792a1;font-size:9px}.activity-note{padding-top:10px;border-top:1px solid #edf0f4}</style>
