<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { salesRequest } from '../salesApi'
const props = defineProps<{ tenantId: string }>()
const cohorts = ref<any[]>([]); const cohortId = ref(''); const report = ref<any>(null); const busy = ref(false); const error = ref(''); const cohortName = ref('Sprint 7 internal simulated pilot')
const metricNames: Record<string, string> = { prospects_imported:'Imported prospects', valid_prospects:'Valid rows', duplicates:'Duplicates', websites_analyzed:'Websites analyzed', analysis_failures:'Analysis failures', leads_scored:'Leads scored', high_priority:'High priority', marketing_drafts:'Drafts generated', drafts_awaiting_approval:'Awaiting approval', approved_marketing_drafts:'Approved drafts', sandbox_messages_sent:'Sandbox sent', replies:'Replies', qualified_leads:'Qualified leads', opportunities:'Opportunities', meetings:'Meetings', proposals:'Proposals', average_processing_time_seconds:'Avg import seconds' }
const funnelNames: Record<string,string> = { imported:'Imported', analyzed:'Analyzed', scored:'Scored', drafted:'Drafted', approved:'Approved', sent:'Sent', replied:'Replied', qualified:'Qualified', opportunity:'Opportunity', meeting:'Meeting', proposal:'Proposal' }
const rates = computed(() => Object.entries(report.value?.rates_percent ?? {}))
async function load() { busy.value = true; error.value = ''; try { cohorts.value = (await salesRequest('/pilot/cohorts', props.tenantId)).data ?? []; report.value = await salesRequest(`/pilot/dashboard${cohortId.value ? `?cohort_id=${encodeURIComponent(cohortId.value)}` : ''}`, props.tenantId) } catch (e) { error.value = e instanceof Error ? e.message : 'Pilot metrics are temporarily unavailable.' } finally { busy.value = false } }
async function createCohort() { try { await salesRequest('/pilot/cohorts', props.tenantId, 'POST', { name: cohortName.value, starts_on: new Date().toISOString().slice(0,10), status:'active' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Unable to create cohort.' } }
watch(() => [props.tenantId, cohortId.value], () => { void load() }); onMounted(() => { void load() })
</script>
<template>
  <section class="pilot-dashboard panel">
    <div class="pilot-head"><div><span class="eyebrow">PILOT OPERATIONS</span><h2>Acquisition pilot</h2><p>Counts and rates come from tenant-scoped workflow records. Simulated events are not commercial outcomes.</p></div><span v-if="report" class="simulated" :class="{ live: !report.simulated }">{{ report.simulated ? 'NO LIVE OUTBOUND RECORDS' : 'LIVE PROVIDER RECORDS PRESENT' }}</span></div>
    <div class="pilot-tools"><label>Filter by cohort<select v-model="cohortId"><option value="">All pilot imports</option><option v-for="cohort in cohorts" :key="cohort.id" :value="cohort.id">{{ cohort.name }}</option></select></label><input v-model="cohortName" aria-label="New cohort name" maxlength="160"/><button class="quiet" @click="createCohort">＋ Create cohort</button><button class="quiet" :disabled="busy" @click="load">↻ Refresh</button></div>
    <p v-if="error" class="pilot-error" role="alert">{{ error }}</p><div v-if="busy && !report" class="pilot-empty">Loading pilot metrics…</div>
    <template v-else-if="report"><div class="pilot-metrics"><article v-for="(value,key) in report.metrics" :key="key"><small>{{ metricNames[String(key)] || key }}</small><b>{{ value }}</b></article></div><div class="pilot-lower"><section><h3>Workflow funnel</h3><div class="funnel-list"><div v-for="(value,key) in report.funnel" :key="key"><span>{{ funnelNames[String(key)] || key }}</span><b>{{ value }}</b></div></div></section><section><h3>Measured rates</h3><div class="rate-list"><div v-for="[key,value] in rates" :key="key"><span>{{ key.replaceAll('_',' ') }}</span><b>{{ value === null ? '—' : `${value}%` }}</b></div></div><small class="rate-note">Zero denominator is shown as —. Review KPI definitions in Sprint 7 documentation.</small></section></div></template>
  </section>
</template>
<style scoped>
.pilot-dashboard{display:grid;gap:13px;padding:17px;min-width:0}.pilot-head,.pilot-tools{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.pilot-head h2{font-size:15px;margin:3px 0;color:#263851}.pilot-head p{font-size:10px;color:#78869a;margin:0}.simulated{padding:7px 9px;border-radius:20px;background:#fff7e5;color:#806628;font-size:9px;font-weight:800;white-space:nowrap}.pilot-tools label{display:flex;align-items:center;gap:8px;font-size:10px;color:#718096}.pilot-tools input,.pilot-tools select{height:34px;max-width:220px;border:1px solid #dfe5ed;border-radius:7px;padding:5px 8px;background:#fff;color:#273a54}.pilot-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.pilot-metrics article{display:grid;gap:7px;padding:11px;border:1px solid #e8ecf2;border-radius:9px;min-width:0}.pilot-metrics small{font-size:9px;color:#718096}.pilot-metrics b{font-size:18px;color:#273a54}.pilot-lower{display:grid;grid-template-columns:1fr 1.4fr;gap:12px}.pilot-lower section{padding:12px;border:1px solid #e8ecf2;border-radius:9px;min-width:0}.pilot-lower h3{font-size:11px;margin:0 0 8px;color:#425674}.funnel-list,.rate-list{display:grid;gap:5px}.funnel-list div,.rate-list div{display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-bottom:1px solid #f0f2f6;font-size:9px;text-transform:capitalize;color:#718096}.funnel-list b,.rate-list b{color:#344760;white-space:nowrap}.rate-list{grid-template-columns:repeat(2,minmax(0,1fr));column-gap:12px}.rate-note,.pilot-empty,.pilot-error{font-size:10px;color:#7a8799}.pilot-error{color:#a34539}@media(max-width:850px){.pilot-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.pilot-lower{grid-template-columns:1fr}}@media(max-width:480px){.pilot-tools{align-items:stretch}.pilot-tools input,.pilot-tools select{max-width:100%;min-width:0}.rate-list{grid-template-columns:1fr}}
</style>
