<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { salesRequest } from '../salesApi'
const props = defineProps<{ tenantId: string }>()
const cohorts = ref<any[]>([]); const cohortId = ref(''); const report = ref<any>(null); const busy = ref(false); const error = ref(''); const cohortName = ref('Sprint 7B — Controlled Real Prospect Pilot')
const metricNames: Record<string, string> = { prospects_imported:'Imported prospects', valid_prospects:'Valid rows', duplicates:'Duplicates', crawl_completed:'Crawl completed', crawl_partial:'Crawl partial', crawl_failed:'Crawl failed', intelligence_generated:'Website Intelligence generated', intelligence_failed:'Intelligence historical failure', intelligence_current_success:'Intelligence current success', intelligence_current_failure:'Intelligence current failure', intelligence_historical_failure:'Intelligence historical failure', leads_scored:'AI scores available (advisory)', insufficient_evidence:'Score insufficient evidence', score_unclassified:'Score legacy/unclassified', score_current:'Score current', score_insufficient_evidence:'Score insufficient evidence', score_legacy_unclassified:'Score legacy/unclassified', human_reviewed:'Reviewed by a person', awaiting_human_review:'Awaiting human review', human_priority_high:'Human priority · High', human_priority_medium:'Human priority · Medium', human_priority_low:'Human priority · Low', human_priority_needs_more_evidence:'Human priority · Needs more evidence', human_priority_not_a_fit:'Human priority · Not a fit', human_service_selected:'Human service selected', human_no_service_selected:'No applicable service', human_needs_discovery:'Service decision · Needs discovery', high_priority:'AI score high (advisory)', marketing_drafts:'Drafts generated', drafts_awaiting_approval:'Awaiting approval', approved_marketing_drafts:'Approved drafts', sandbox_messages_sent:'Sandbox sent', replies:'Replies', qualified_leads:'Qualified leads', opportunities:'Opportunities', meetings:'Meetings', proposals:'Proposals', average_processing_time_seconds:'Avg import seconds' }
const funnelNames: Record<string,string> = { imported:'Imported prospects', crawl_completed:'Crawl completed', crawl_partial:'Crawl partial', crawl_failed:'Crawl failed', intelligence_generated:'Intelligence generated', intelligence_failed:'Intelligence failed', scored:'Lead scored', insufficient_evidence:'Insufficient evidence', score_unclassified:'Score unclassified', human_reviewed:'Human reviewed', drafted:'Drafted', approved:'Approved', sent:'Sent', replied:'Replied', qualified:'Qualified', opportunity:'Opportunity', meeting:'Meeting', proposal:'Proposal' }
const rates = computed(() => Object.entries(report.value?.rates_percent ?? {}))
const pilotMetrics = computed(() => report.value?.metrics ?? {})
const progressKeys = ['prospects_imported', 'crawl_completed', 'intelligence_generated', 'awaiting_human_review', 'human_reviewed']
const humanDecisionKeys = ['human_priority_high', 'human_priority_medium', 'human_priority_low', 'human_priority_needs_more_evidence', 'human_priority_not_a_fit', 'human_service_selected', 'human_no_service_selected', 'human_needs_discovery']
const advisoryKeys = ['leads_scored', 'insufficient_evidence', 'score_unclassified', 'high_priority']
const metricsFor = (keys: string[]) => keys.filter((key) => pilotMetrics.value[key] !== undefined).map((key) => [key, pilotMetrics.value[key]] as const)
const rateName = (key: string) => ({ failed_job_rate: 'Import processing failure rate', crawl_completion_rate: 'Latest crawl completion rate' } as Record<string, string>)[key] || key.replaceAll('_', ' ')
async function load() { busy.value = true; error.value = ''; try { cohorts.value = (await salesRequest('/pilot/cohorts', props.tenantId)).data ?? []; report.value = await salesRequest(`/pilot/dashboard${cohortId.value ? `?cohort_id=${encodeURIComponent(cohortId.value)}` : ''}`, props.tenantId) } catch (e) { error.value = e instanceof Error ? e.message : 'Pilot metrics are temporarily unavailable.' } finally { busy.value = false } }
async function createCohort() { try { await salesRequest('/pilot/cohorts', props.tenantId, 'POST', { name: cohortName.value, starts_on: new Date().toISOString().slice(0,10), status:'active', data_classification:'real' }); await load() } catch (e) { error.value = e instanceof Error ? e.message : 'Unable to create cohort.' } }
watch(() => [props.tenantId, cohortId.value], () => { void load() }); onMounted(() => { void load() })
</script>
<template>
  <section class="pilot-dashboard panel">
    <div class="pilot-head"><div><span class="eyebrow">PILOT OPERATIONS</span><h2>Acquisition pilot</h2><p>Human-assisted intelligence workspace. AI scores and service suggestions are advisory; human priority and service decisions are reported separately.</p></div><span v-if="report" class="simulated" :class="{ live: report.cohort?.data_classification === 'real' }">{{ report.cohort?.data_classification?.toUpperCase() || 'ALL COHORTS' }} COHORT · {{ report.simulated ? 'NO LIVE OUTBOUND' : 'LIVE OUTBOUND RECORDS' }}</span></div>
    <div class="pilot-tools"><label>Filter by cohort<select v-model="cohortId"><option value="">All pilot imports</option><option v-for="cohort in cohorts" :key="cohort.id" :value="cohort.id">{{ cohort.name }} · {{ (cohort.data_classification || 'real').toUpperCase() }}</option></select></label><input v-model="cohortName" aria-label="New cohort name" maxlength="160"/><button class="quiet" @click="createCohort">＋ Create cohort</button><button class="quiet" :disabled="busy" @click="load">↻ Refresh</button></div>
    <p v-if="error" class="pilot-error" role="alert">{{ error }}</p><div v-if="busy && !report" class="pilot-empty">Loading pilot metrics…</div>
    <template v-else-if="report"><div v-if="report.sales_intelligence_mode" class="mode-banner"><b>HUMAN-ASSISTED MODE</b><span>AI findings and scores are advisory. Service selection, priority, and next actions remain human decisions.</span></div><section class="metric-section"><div class="metric-section-head"><h3>Pilot progress</h3><small>Prospect processing and review workflow</small></div><div class="pilot-metrics"> <article v-for="[key,value] in metricsFor(progressKeys)" :key="key"><small>{{ metricNames[key] || key }}</small><b>{{ value }}</b></article></div></section><section class="metric-section human-metrics"><div class="metric-section-head"><h3>Human decisions</h3><small>Recorded selections and priorities</small></div><div class="pilot-metrics"> <article v-for="[key,value] in metricsFor(humanDecisionKeys)" :key="key"><small>{{ metricNames[key] || key }}</small><b>{{ value }}</b></article><p v-if="!metricsFor(humanDecisionKeys).length" class="metric-empty">No human decisions recorded yet.</p></div></section><section class="metric-section advisory-metrics"><div class="metric-section-head"><h3>AI advisory</h3><small>Informational only · does not qualify or advance a prospect</small></div><div class="pilot-metrics"> <article v-for="[key,value] in metricsFor(advisoryKeys)" :key="key"><small>{{ metricNames[key] || key }}</small><b>{{ value }}</b></article><p v-if="!metricsFor(advisoryKeys).length" class="metric-empty">No advisory scores available yet.</p></div></section><div class="pilot-lower"><section><h3>Workflow funnel</h3><div class="funnel-list"><div v-for="(value,key) in report.funnel" :key="key"><span>{{ funnelNames[String(key)] || key }}</span><b>{{ value }}</b></div></div></section><section><h3>Measured rates</h3><div class="rate-list"><div v-for="[key,value] in rates" :key="key"><span>{{ rateName(String(key)) }}</span><b>{{ value === null ? '—' : `${value}%` }}</b></div></div><small class="rate-note">Zero denominator is shown as —. Review KPI definitions in Sprint 7 documentation.</small></section></div></template>
  </section>
</template>
<style scoped>
.pilot-dashboard{display:grid;gap:16px;padding:20px;min-width:0}.mode-banner{display:flex;gap:12px;align-items:center;padding:12px 14px;border:1px solid #d9d4ee;border-radius:10px;background:#f7f5fd;color:#51477e;font-size:12px}.mode-banner b{font-size:10px;letter-spacing:.07em;white-space:nowrap}.pilot-head,.pilot-tools{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.pilot-head h2{font-size:18px;margin:3px 0;color:#263851}.pilot-head p{font-size:12px;color:#68778c;margin:0}.simulated{padding:7px 9px;border-radius:20px;background:#fff7e5;color:#806628;font-size:10px;font-weight:800;white-space:nowrap}.pilot-tools label{display:flex;align-items:center;gap:8px;font-size:11px;color:#718096}.pilot-tools input,.pilot-tools select{height:38px;max-width:250px;border:1px solid #dfe5ed;border-radius:8px;padding:6px 10px;background:#fff;color:#273a54}.metric-section{display:grid;gap:9px}.metric-section-head{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.metric-section-head h3{margin:0;color:#344257;font-size:14px}.metric-section-head small{color:#7d899a;font-size:11px}.human-metrics{padding:14px;border:1px solid #dbe5fa;border-radius:12px;background:#f7f9ff}.advisory-metrics{padding:14px;border:1px solid #e5def5;border-radius:12px;background:#faf8ff}.pilot-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.pilot-metrics article{display:grid;gap:7px;padding:13px;border:1px solid #e8ecf2;border-radius:10px;background:#fff;min-width:0}.pilot-metrics small{font-size:11px;color:#718096}.pilot-metrics b{font-size:21px;color:#273a54}.metric-empty{grid-column:1/-1;color:#7b8798;font-size:12px;margin:0;padding:8px}.pilot-lower{display:grid;grid-template-columns:1fr 1.4fr;gap:14px}.pilot-lower section{padding:15px;border:1px solid #e8ecf2;border-radius:10px;min-width:0}.pilot-lower h3{font-size:13px;margin:0 0 9px;color:#425674}.funnel-list,.rate-list{display:grid;gap:5px}.funnel-list div,.rate-list div{display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #f0f2f6;font-size:11px;text-transform:capitalize;color:#718096}.funnel-list b,.rate-list b{color:#344760;white-space:nowrap}.rate-list{grid-template-columns:repeat(2,minmax(0,1fr));column-gap:12px}.rate-note,.pilot-empty,.pilot-error{font-size:11px;color:#7a8799}.pilot-error{color:#a34539}@media(max-width:850px){.pilot-metrics{grid-template-columns:repeat(3,minmax(0,1fr))}.pilot-lower{grid-template-columns:1fr}}@media(max-width:560px){.pilot-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.pilot-tools{align-items:stretch}.pilot-tools input,.pilot-tools select{max-width:100%;min-width:0}.rate-list{grid-template-columns:1fr}.mode-banner{align-items:flex-start;flex-direction:column}}
</style>
