<script setup lang="ts">
import { onMounted, ref } from 'vue'

const props = defineProps<{ tenantId: string }>()
const emit = defineEmits<{ navigate: [page: string] }>()
const busy = ref(false)
const error = ref('')
const notice = ref('')
const services = ref<any[]>([])
const knowledge = ref<any[]>([])
const ai = ref<any[]>([])
const scoring = ref<any>(null)
const messaging = ref<any>({ provider: 'fake', enabled: false, from_name: '', from_email: '', reply_to_email: '', hourly_limit: 60, daily_limit: 500 })
const calendar = ref<any>({ provider: 'fake', enabled: false, default_timezone: 'UTC', owner_timezone: 'UTC', meeting_duration_minutes: 30, buffer_before_minutes: 0, buffer_after_minutes: 0, minimum_notice_minutes: 60, maximum_horizon_days: 30, allowed_weekdays: [1,2,3,4,5], working_hours_start: '09:00', working_hours_end: '17:00', meeting_title_template: 'Discovery meeting with {{company}}', meeting_description_template: '', default_owner_user_id: null })
function csrf() { return decodeURIComponent(document.cookie.split('; ').find((row) => row.startsWith('XSRF-TOKEN='))?.split('=')[1] ?? '') }
async function api(path: string, method = 'GET', body?: unknown) {
  const response = await fetch('/api/v1' + path, { method, credentials: 'include', headers: { Accept: 'application/json', 'X-Tenant-ID': props.tenantId, ...(body === undefined ? {} : { 'Content-Type': 'application/json', 'X-XSRF-TOKEN': csrf() }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) })
  const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message ?? `Request failed (${response.status}).`); return data
}
async function load() {
  error.value = ''
  try { [services.value, knowledge.value, ai.value, scoring.value, messaging.value, calendar.value] = await Promise.all([api('/tenant-services'), api('/marketing-configuration/knowledge'), api('/ai-configurations'), api('/scoring-rules'), api('/messaging-configuration'), api('/scheduling-configuration')]) }
  catch (e) { error.value = e instanceof Error ? e.message : 'Unable to load setup status.' }
}
async function save(path: string, value: any, label: string) { busy.value = true; error.value = ''; notice.value = ''; try { Object.assign(value, await api(path, 'PUT', value)); notice.value = `${label} saved.` } catch (e) { error.value = e instanceof Error ? e.message : `Unable to save ${label.toLowerCase()}.` } finally { busy.value = false } }
onMounted(() => void load())
</script>

<template>
  <div class="setup-workspace">
    <div v-if="error" class="notice">{{ error }} <button class="quiet" @click="load">Retry</button></div>
    <div v-if="notice" class="notice success-notice">{{ notice }}</div>
    <section class="setup-intro panel"><div><div class="eyebrow">TENANT READINESS</div><h2>Get your workspace ready to operate</h2><p>Configuration reflects saved tenant settings. Provider labels describe configured mode; they do not verify external connectivity.</p></div><button class="quiet" @click="load">↻ Refresh status</button></section>
    <div class="setup-grid">
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">⌂</span><h3>Organization</h3></div><span class="pill muted">Limited</span></div><p>Workspace identity is available. Business profile fields are not part of the current backend.</p><small>BACKEND FEATURE REQUIRED for editable organization profile.</small></article>
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">♙</span><h3>Team &amp; access</h3></div><span class="pill muted">Unavailable</span></div><p>Users and tenant membership roles are enforced at sign-in.</p><small>BACKEND FEATURE REQUIRED for invitations and member administration.</small></article>
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">☷</span><h3>ICP &amp; scoring</h3></div><span class="pill">{{ scoring?.version ? 'Configured' : 'Incomplete' }}</span></div><p>Ideal customer profile affects qualification and lead scoring. It does not discover companies externally.</p><button class="quiet" @click="emit('navigate', 'ICP Configuration')">Configure ICP →</button></article>
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">✦</span><h3>Services &amp; knowledge</h3></div><span class="pill">{{ services.length || knowledge.length ? 'Configured' : 'Incomplete' }}</span></div><p>{{ services.length }} catalog services · {{ knowledge.filter((x:any) => x.status === 'approved').length }} approved knowledge items</p><small>Only approved tenant knowledge is eligible for marketing generation.</small><button class="quiet" @click="emit('navigate', 'Services & Pricing')">Manage services &amp; pricing →</button><button class="quiet" @click="emit('navigate', 'knowledge')">Review approved knowledge →</button></article>
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">◇</span><h3>Pricing</h3></div><span class="pill">{{ services.some((x:any) => x.active) ? 'Configured' : 'Incomplete' }}</span></div><p>Proposal commercials are sourced from approved catalog services and human-authorized overrides.</p><button class="quiet" @click="emit('navigate', 'Services & Pricing')">Open pricing catalog →</button></article>
      <article class="panel setup-card"><div class="setup-card-head"><div><span class="setup-icon">✳</span><h3>AI routing</h3></div><span class="pill">{{ ai.length ? 'Configured · not tested' : 'Incomplete' }}</span></div><p>{{ ai.length }} task routes are configured. Live provider calls have not been verified by this screen.</p><button class="quiet" @click="emit('navigate', 'AI Configuration')">Configure AI tasks →</button></article>
    </div>
    <div class="provider-grid">
      <section class="panel config-form"><div class="provider-title"><div><div class="eyebrow">OUTBOUND MESSAGING</div><h3>Messaging settings</h3><p>Queue and ledger testing only. No external email is sent.</p></div><span class="state-badge">TEST MODE · {{ messaging.provider || 'fake' }}</span></div>
        <div class="setup-fields"><label>Provider<input value="Fake provider" disabled /></label><label>From name<input v-model="messaging.from_name" maxlength="255" /></label><label>From email<input v-model="messaging.from_email" type="email" maxlength="255" /></label><label>Reply-to<input v-model="messaging.reply_to_email" type="email" maxlength="255" /></label><label>Hourly limit<input v-model.number="messaging.hourly_limit" type="number" min="1" max="1000" /></label><label>Daily limit<input v-model.number="messaging.daily_limit" type="number" min="1" max="10000" /></label></div>
        <label class="inline-check"><input v-model="messaging.enabled" type="checkbox" /> Enable fake outbound execution</label><button class="primary" :disabled="busy" @click="save('/messaging-configuration', messaging, 'Messaging configuration')">Save messaging settings</button>
      </section>
      <section class="panel config-form"><div class="provider-title"><div><div class="eyebrow">MEETING SCHEDULING</div><h3>Calendar settings</h3><p>Scheduling uses the local fake provider; no live calendar is connected.</p></div><span class="state-badge">TEST MODE · {{ calendar.provider || 'fake' }}</span></div>
        <div class="setup-fields"><label>Owner user ID<input v-model.number="calendar.default_owner_user_id" type="number" min="1" /></label><label>Workspace timezone<select v-model="calendar.default_timezone"><option>UTC</option><option>Asia/Kolkata</option><option>America/New_York</option><option>Europe/London</option></select></label><label>Owner timezone<select v-model="calendar.owner_timezone"><option>UTC</option><option>Asia/Kolkata</option><option>America/New_York</option><option>Europe/London</option></select></label><label>Duration<select v-model.number="calendar.meeting_duration_minutes"><option :value="30">30 minutes</option><option :value="45">45 minutes</option><option :value="60">60 minutes</option></select></label><label>Notice (minutes)<input v-model.number="calendar.minimum_notice_minutes" type="number" min="0" max="10080" /></label><label>Booking horizon (days)<input v-model.number="calendar.maximum_horizon_days" type="number" min="1" max="90" /></label><label>Buffer before (minutes)<input v-model.number="calendar.buffer_before_minutes" type="number" min="0" max="120" /></label><label>Buffer after (minutes)<input v-model.number="calendar.buffer_after_minutes" type="number" min="0" max="120" /></label><label>Workday start<input v-model="calendar.working_hours_start" type="time" /></label><label>Workday end<input v-model="calendar.working_hours_end" type="time" /></label><label class="weekdays">Working days <span v-for="day in [{n:1,l:'Mon'},{n:2,l:'Tue'},{n:3,l:'Wed'},{n:4,l:'Thu'},{n:5,l:'Fri'},{n:6,l:'Sat'},{n:7,l:'Sun'}]" :key="day.n"><input v-model="calendar.allowed_weekdays" type="checkbox" :value="day.n"/> {{ day.l }}</span></label></div>
        <label class="inline-check"><input v-model="calendar.enabled" type="checkbox" /> Enable fake scheduling</label><button class="primary" :disabled="busy" @click="save('/scheduling-configuration', calendar, 'Calendar configuration')">Save calendar settings</button>
      </section>
    </div>
    <section class="panel setup-storage"><h3>Storage &amp; integrations</h3><div class="setup-status-row"><b>Private document storage</b><span class="pill muted">Configured · not runtime verified</span></div><div class="setup-status-row"><b>AI provider connectivity</b><span class="pill muted">Not verified</span></div><div class="setup-status-row"><b>Automation policies</b><span>Review how actions are controlled.</span><button class="quiet" @click="emit('navigate', 'AI Automation Policies')">Manage automation →</button></div></section>
  </div>
</template>

<style scoped>
.setup-workspace{display:grid;gap:14px}.setup-intro{display:flex;justify-content:space-between;align-items:center;gap:14px}.setup-intro h2,.provider-title h3{margin:4px 0;font-size:16px}.setup-intro p,.provider-title p{margin:4px 0 0;color:#788395;font-size:11px}.setup-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.setup-card{display:flex;flex-direction:column;align-items:flex-start;gap:8px;min-height:160px}.setup-card p{margin:0;color:#657184;font-size:11px;line-height:1.5}.setup-card small{color:#8792a1;font-size:9px}.setup-card .quiet{margin-top:auto}.setup-card-head{width:100%;display:flex;justify-content:space-between;align-items:center}.setup-card-head>div{display:flex;align-items:center;gap:8px}.setup-card h3,.setup-storage h3{margin:0;font-size:13px}.setup-icon{display:grid;place-items:center;width:28px;height:28px;border-radius:8px;background:#eff3ff;color:#4e62a5}.setup-card .pill,.setup-storage .pill{padding:5px 8px;border-radius:20px;background:#eff6f1;color:#3c785b;font-size:9px}.setup-card .pill.muted,.setup-storage .pill.muted{background:#f2f4f7;color:#747f8f}.provider-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.config-form{display:flex;flex-direction:column;gap:13px}.provider-title{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}.state-badge{padding:7px 9px;border-radius:20px;background:#fff3e4;color:#a25b08;font-size:9px;font-weight:800;white-space:nowrap}.setup-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.setup-fields label{display:flex;flex-direction:column;gap:5px;color:#56647a;font-size:10px}.setup-fields input,.setup-fields select{min-width:0;width:100%;padding:8px;border:1px solid #e0e5ec;border-radius:6px;background:white;color:#36445a;font:11px 'DM Sans'}.setup-fields input:disabled{color:#808a97;background:#f6f7f9}.inline-check{display:flex;align-items:center;gap:7px;font-size:10px;color:#56647a}.weekdays{grid-column:1/-1}.weekdays span{display:inline-flex;align-items:center;margin:8px 8px 0 0}.weekdays input{width:auto}.setup-storage{display:grid;gap:12px}.setup-status-row{display:flex;align-items:center;gap:12px;padding-top:10px;border-top:1px solid #edf0f4;color:#667386;font-size:11px}.setup-status-row>b{color:#344257;min-width:180px}.setup-status-row .quiet{margin-left:auto}@media(max-width:1000px){.setup-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.provider-grid{grid-template-columns:1fr}}@media(max-width:600px){.setup-grid{grid-template-columns:1fr}.setup-intro,.provider-title{align-items:flex-start;flex-direction:column}.setup-status-row{align-items:flex-start;flex-direction:column}.setup-status-row .quiet{margin:0}}
</style>
